field: 7b08d9ba-8697-43f3-a5a6-c077601b74e4
fieldLayouts:
  c142f187-f1a8-4cb4-93e8-df12f3ceaac0:
    tabs:
      -
        elements:
          -
            fieldUid: f4dacd60-b276-42ca-8a57-ae12ad7878c2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  f4dacd60-b276-42ca-8a57-ae12ad7878c2:
    contentColumnType: text
    fieldGroup: null
    handle: moduleText
    instructions: ''
    name: 'Module Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: moduleText
name: 'Module Text'
sortOrder: 1
