field: c54876c6-2a9b-4883-87d8-98647d6f9bfe
fieldLayouts:
  aed07ede-d287-47ab-b983-32a710737666:
    tabs:
      -
        elements:
          -
            fieldUid: 30dcd176-499b-4431-9d06-78cd8b558e02
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 86f68485-0588-486d-b115-4086c3d18cf6
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  30dcd176-499b-4431-9d06-78cd8b558e02:
    contentColumnType: text
    fieldGroup: null
    handle: linkText
    instructions: ''
    name: 'Link text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  86f68485-0588-486d-b115-4086c3d18cf6:
    contentColumnType: string
    fieldGroup: null
    handle: linkDestination
    instructions: ''
    name: 'link destination'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: navLink
name: 'nav link'
sortOrder: 1
