field: 4d4e15c8-02ad-476e-ba7d-891aa65cdfb4
fieldLayouts:
  0aaa4311-8133-4c9c-b2eb-6d0b76d56ca3:
    tabs:
      -
        elements:
          -
            fieldUid: 26fc1153-6823-4eb9-bebb-978cbe27b950
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  26fc1153-6823-4eb9-bebb-978cbe27b950:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: text
name: Text
sortOrder: 1
