enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  5767ef54-af4c-422c-8628-8c8f024eef96:
    enabledByDefault: true
    hasUrls: true
    template: home
    uriFormat: __home__
type: single
